version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    groups:
      react-next:
        dependency-type: production
        patterns:
          - "react"
          - "next"
      nivo:
        dependency-type: production
        patterns:
          - "*nivo*"
      antd:
        dependency-type: production
        patterns:
          - "antd"
          - "@antd*"

      dev-dependencies:
        dependency-type: production
        patterns:
          - "*"
      prod-dependencies:
        dependency-type: production
        patterns:
          - "*"
