version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "smallkirby"
    labels:
      - "dependencies"
    groups:
      react-next:
        dependency-type: production
        patterns:
          - "react"
          - "next"
      dev-dependencies:
        dependency-type: production
        patterns:
          - "*"
      prod-dependencies:
        dependency-type: production
        patterns:
          - "*"
